services:
  - type: worker
    name: osint-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8683516544:AAGyndEbkMW1wsbXTFIbFMg8AVA_uZ__bSk
      - key: PORT
        value: 8080
